export const ITEMS_PER_PAGE = [5, 10, 15, 20, 50, 100];
export const MANAGEMENT_LEVELS: string[] = [
  'owner',
  'founder',
  'co-founder',
  'cxo',
  'ceo',
  'cto',
  'cfo',
  'coo',
  'chief strategy officer',
  'chief growth officer',
  'chief marketing officer',
  'chief product officer',
  'chief people officer',
  'partner',
  'vice president',
  'senior vice president',
  'assistant vice president',
  'associate vice president',
  'vp',
  'svp',
  'avp',
  'head',
  'director',
  'managing director',
  'associate director',
  'assistant director',
  'general manager',
  'senior manager',
  'manager',
  'lead',
  'team lead',
  'consultant',
  'senior consultant',
  'principal',
  'specialist',
  'analyst',
  'senior analyst',
  'entry',
  'junior',
  'intern',
  'trainee',
];

export const JOB_FUNCTIONS: string[] = [
  'product',
  'engineering & technical',
  'design',
  'education',
  'finance',
  'human resources',
  'information technology',
  'legal',
  'marketing',
  'medical & health',
  'operations',
  'sales',
  'consulting',
  'business development',
];
